---
title: "Homepage"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
    css: style.css
    includes: 
      in_header: header.html
      after_body: footer.html
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About
***

I'm a learning programmer focused on topics like Machine Learning, AI, and a bit of Emulation. I've mainly coded in languages like C#/Java, Python, and Rust so far but I'm starting to learn other languages like C and have experience in Octave/Matlab. 

To see the code I've written and compiled for this website, click [here](https://github.com/ThunderingWest4/thunderingwest4.github.io). The reason that some of the HTML files look like gibberish is because I wrote the code/text in R Markdown files and compiled it from there into HTML. 
To see my github account which has repositories of all of my projects, completed and finished, click [here](https://github.com/ThunderingWest4/). 

## Projects
***
### Completed

I have several completed projects, which you can see (and experiment with!) by hovering over the "Completed Projects" tab in the header menu at the top of the page. 

### In Progress
At the moment, I'm working on a couple of projects: 

+ Chip-8 Emulator
+ Useless Box


When they're complete, I'll put them on this website. For the ones that include more physical components and can't be put on a website, I'll show my code for that project as well as my thought process and design for the final product as well as some images of it.

## Pages Under Construction

At the moment, there are several pages on this website that I've added as placeholders of sorts - the tabs are there but it redirects you to an Under Construction page because I haven't had much of a chance to finish building those pages yet. However, I'll have an updated list below of pages that are currently finished, in progress, and not yet started. 

### Finished Pages

Well technically none because I'll always be improving the pages if I find a place to improve them. However, the ones that are probably the most finished and will have minimal revisions are: 

+ The Homepage

### In Progress

I'm currently focused on finishing the Iris Flower Neural Network Page

### Not Yet Started

The not yet started pages on the website with just placeholders are: 

+ Chip-8 Emulator
+ Hunt The Wumpus
+ Pathfinding Snake
