---
title: "Homepage"
output: 
  html_document:
    toc: TRUE
    toc_depth: 3
    toc_float: TRUE
    css: style.css
    includes: 
      in_header: header.html
      after_body: footer.html
fontsize: 12pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## About
***

I'm a learning programmer focused on topics like Machine Learning, AI, and a bit of Emulation. I've mainly coded in languages like C#/Java, Python, and Rust so far but I'm starting to learn other languages like C and have experience in Octave/Matlab. 

## Projects
***
### Completed

I have several completed projects, which you can see (and experiment with!) by hovering over the "Completed Projects" tab in the header menu at the top of the page. 

***

### In Progress

At the moment, I'm working on a couple of projects: 

+ Chip-8 Emulator
+ Useless Box


When they're complete, I'll put them on this website. For the ones that include more physical components and can't be put on a website, I'll show my code for that project as well as my thought process and design for the final product as well as some images of it.

## Pages Under Construction

At the moment, the pages for the Chip-8 Emulator and Useless Box are under construction. I have several projects going on right now so as soon as I get them under control and hopefully finish one or two, these pages will start being built. 
